[tool.poetry]
name = "atlantic_server"
version = "0.3.5"
description = "Server side of an application of an Aircraft Technical Log"
authors = ["Matthieu Nué <matthieu.nue@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^2.2"
djangorestframework = "^3"
drf-nested-routers = "^0.91"
django-filter = "^2"
lxml = "^4"
pygit2 = "~1.2"
cffi = "^1.14.0"
wheel = "^0.35.1"
mysqlclient = "^2"

[tool.poetry.dev-dependencies]
pytest = "^3"
pylint = "^2"
black = {version = "^19.10b0", allow-prereleases = true}
pylint-django = "^2"

[tool.poetry.scripts]
atlantic_server="atlantic_server.manage:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
