# Generated by Django 2.2.6 on 2019-10-24 21:06

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xpos', models.FloatField()),
                ('ypos', models.FloatField()),
                ('zpos', models.FloatField()),
                ('xtarget', models.FloatField()),
                ('ytarget', models.FloatField()),
                ('ztarget', models.FloatField()),
                ('zoom', models.FloatField(default=1.0)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gltf', models.TextField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('msn', models.IntegerField()),
                ('gltf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atl.ModelPlane')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('ATA', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('nature', models.CharField(choices=[('D', 'Damage'), ('W', 'Work'), ('O', 'Other')], default='O', max_length=1)),
                ('progress', models.CharField(choices=[('O', 'Open'), ('F', 'Fixed'), ('C', 'Checked')], default='O', max_length=1)),
                ('tour', models.IntegerField(default=0)),
                ('camera', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atl.Camera')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atl.Plane')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('progress', models.CharField(blank=True, choices=[('O', 'Open'), ('F', 'Fixed'), ('C', 'Checked')], max_length=1)),
                ('image', models.TextField(blank=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='atl.Page')),
            ],
            options={
                'ordering': ['edited'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atl.Plane'),
        ),
    ]
